# Generated by Django 3.1 on 2020-08-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='due_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='importance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
