# Generated by Django 3.1 on 2020-08-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
