# Generated by Django 3.1 on 2020-08-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingList', '0002_auto_20200819_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='list',
            new_name='list_name',
        ),
    ]
