# Generated by Django 3.1 on 2020-08-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingList', '0004_auto_20200821_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='list_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingList.shoppinglistlist', to_field='list_name'),
        ),
        migrations.AlterField(
            model_name='shoppinglistlist',
            name='list_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
