# Generated by Django 3.1 on 2020-08-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingList', '0006_auto_20200821_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingList.shoppinglistcategory'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='list_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingList.shoppinglistlist'),
        ),
    ]
